config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'

  resources :posts do
    resources :comments, only: %i[create edit update], module: 'posts'
    resources :likes, only: %i[create destroy], module: 'posts'
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: :user_id, inverse_of: :posts
  belongs_to :post_category, inverse_of: :posts

  has_many :comments, class_name: 'PostComment', inverse_of: :post, dependent: :destroy
  has_many :likes, class_name: 'PostLike', inverse_of: :post, dependent: :destroy

  validates :title, :body, presence: true
end

app/models/post_category.rb
# frozen_string_literal: true

class PostCategory < ApplicationRecord
  has_many :posts, inverse_of: :post_category, dependent: :destroy

  validates :name, presence: true
end

app/models/post_comment.rb
# frozen_string_literal: true

class PostComment < ApplicationRecord
  has_ancestry

  belongs_to :creator, class_name: 'User', foreign_key: :user_id, inverse_of: :post_comments
  belongs_to :post

  validates :content, presence: true
end

app/models/post_like.rb
# frozen_string_literal: true

class PostLike < ApplicationRecord
  belongs_to :user
  belongs_to :post, counter_cache: true

  validates :post, uniqueness: { scope: :user_id }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts,
           dependent: :destroy,
           inverse_of: :creator

  has_many :post_comments,
           dependent: :destroy,
           inverse_of: :creator

  has_many :post_likes,
           dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = t('flash.not_authorized')
    redirect_to(request.referer || root_path)
  end
end

app/controllers/posts/comments_controller.rb
# frozen_string_literal: true

class Posts::CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post
  before_action :set_comment, only: %i[edit update]

  def create
    @comment = @post.comments.build(comment_params)
    @comment.creator = current_user
    flash[:alert] = t('flash.empty_comment') unless @comment.save
    redirect_to post_path(@post)
  end

  def edit; end

  def update
    if @comment.update(comment_params)
      redirect_to post_path(@post)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:post_comment).permit(:content, :parent_id)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = @post.comments.find(params[:id])
  end
end

app/controllers/posts/likes_controller.rb
# frozen_string_literal: true

class Posts::LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def create
    @like = @post.likes.build(user: current_user)
    @like.save

    redirect_to @post
  end

  def destroy
    @like = @post.likes.find_by(user: current_user)
    @like.destroy

    redirect_to @post
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authorize_post, only: %i[edit update destroy]

  def index
    @posts = Post.all
  end

  def show
    @comment = @post.comments.build
    @comment_collection = @post.comments.filter { |comment| comment.is_root? && comment.id }
    @current_user_like = @post.likes.find_by(user: current_user)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to post_path(@post), notice: t('flash.post_created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @post.update post_params
      redirect_to post_path(@post), notice: t('flash.post_updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy

    redirect_to posts_path, notice: t('flash.post_destroyed')
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :post_category_id)
  end

  def authorize_post
    authorize @post
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/posts/comments_helper.rb
# frozen_string_literal: true

module Posts::CommentsHelper
end

app/helpers/posts/likes_helper.rb
# frozen_string_literal: true

module Posts::LikesHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = t('.title')
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body.d-flex.flex-column.h-100
    header
      nav.navbar.navbar-expand-md.navbar-dark.bg-dark
        .container-fluid
          = link_to root_path, class: 'navbar-brand'
            = t('.header')
          div#navbarCollapse.collapse.navbar-collapse
            ul.navbar-nav.ms-auto
              - if user_signed_in?
                  li.nav-item
                    = link_to t('.new_post'), new_post_path, class: 'nav-link'
                  li.nav-item
                    = link_to t('.sign_out'), destroy_user_session_path, method: :delete, class: 'dropdown-item nav-link link-dark'
              - else
                  li.nav-item
                    = link_to t('.sign_in'), new_user_session_path, class: 'nav-link link-dark'
                  li.nav-item
                    = link_to t('.sign_up'), new_user_registration_path, class: 'nav-link link-dark'
    div.container.my-4
      - if flash[:notice]
        .container.my-2
          - flash.each do |_type, msg|
            .alert.alert-info
              = msg
      - if flash[:alert]
        .container.my-2
          - flash.each do |_type, msg|
            .alert.alert-danger
              = msg
      = yield

app/views/posts/_form.html.slim
= simple_form_for post do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  = f.input :title
  = f.input :body, as: :text
  = f.association :post_category, prompt: true

  = f.button :submit, class: 'btn-primary my-3'
end

app/views/posts/_post.html.slim
.card.mb-4
  .card-body
    h5.card-title
      = link_to post.title, post, class: 'text-decoration-none'
    .card-text.mb-2
      = post.body
    .card-text.text-end.mb-1
      small.me-3.text-muted
          = t('.likes_count', count: post.likes.size)
          i.fas.fa-heart
      small.me-3.text-muted
        = t('.time_ago', date: time_ago_in_words(post.created_at))
      small.text-muted
        = post.creator.email

app/views/posts/comments/_comment.html.slim
.card.mb-4
  .card-header.small.mb-2.d-flex
    .mr-auto.d-flex(id="comment-#{comment.id}")
      span.font-weight-bold
        = comment.creator.email
      span.mx-2.font-weight-light
        = t('.time_ago', date: time_ago_in_words(comment.created_at))
  .card-body.d-flex
    .w-100
      .mb-3
        = comment.content
      - if comment.creator == @current_user
        small
          = link_to t(:edit), edit_post_comment_path(@post, comment), class: 'me-2'
  - if comment.has_children?
    .small
      = render partial: 'posts/comments/nested_comment', collection: comment.children
  hr.my-2
  .mb-2.mx-4
    a.d-block.small.text-muted.collapsed(data-bs-toggle="collapse" href="#new_post_comment-#{comment.id}" aria-expanded="false" role="button" aria-controls="#new_post_comment-#{comment.id}")
      = t('.respond')
    .collapse(id="new_post_comment-#{comment.id}")
      - if user_signed_in?
        = render 'posts/comments/form', comment: comment.post.comments.new, url: post_comments_path(comment.post), parent_id: comment.id
      - else
        = link_to 'Sign in', new_user_session_path, class: 'nav-link link-dark'
          

app/views/posts/comments/_form.html.slim
= simple_form_for comment, url: url do |f|
  - if local_assigns[:parent_id]
    = f.input :parent_id, as: :hidden, input_html: { value: parent_id }
  = f.input :content, as: :text, input_html: { rows: 3 }

  = f.button :submit, class: 'btn-primary my-3'
end

app/views/posts/comments/_nested_comment.html.slim
.ms-4
  hr.my-2
  .d-flex(id="comment-#{nested_comment.id}")
    .mr-auto
      span.me-2
        = nested_comment.content
      span.me-1
        = nested_comment.creator.email
      span.text-muted
        = l(nested_comment.created_at, format: :short)
  - if nested_comment.creator == @current_user
    small
      = link_to t(:edit), edit_post_comment_path(@post, nested_comment), class: 'me-2'
  hr.my-2
  .mb-2
    a.d-block.small.text-muted.collapsed(data-bs-toggle="collapse" href="#new_post_comment-#{nested_comment.id}" aria-expanded="false" role="button" aria-controls="#new_post_comment-#{nested_comment.id}")
      = t('.respond')
    .collapse(id="new_post_comment-#{nested_comment.id}")
      - if user_signed_in?
        = render 'posts/comments/form', comment: nested_comment.post.comments.new, url: post_comments_path(nested_comment.post), parent_id: nested_comment.id
      - else
        = link_to 'Sign in', new_user_session_path, class: 'nav-link link-dark'

  - if nested_comment.has_children?
    = render partial: 'posts/comments/nested_comment', collection: nested_comment.children

app/views/posts/comments/edit.html.slim
h1.h2.mb-4
  = t('.header')
= render 'posts/comments/form', comment: @comment, url: post_comment_path(@comment.post, @comment)

app/views/posts/edit.html.slim
h1.h2.mb-4
  = t('.header')
= render 'form', post: @post

app/views/posts/index.html.slim
h1
  = t('.header')
div.row
  = render @posts

app/views/posts/new.html.slim
h1.h2.mb-4
  = t('.header')
= render 'form', post: @post

app/views/posts/show.html.slim
ol.breadcrumb.bg-light.p-3
  li.breadcrumb-item
    = link_to root_path
      = t('.all_posts')
  li.breadcrumb-item.active
    = @post.post_category.name
.row.justify-content-center.mt-4
  article.col-12.col-lg-4.col-xl-8
    h1.mb-4.mb-lg-5
      = @post.title
    p.text-break
      = @post.body
    .d-flex.align-items-center.mt-5
      span.me-3
        = @post.creator.email
      span
        = t('.time_ago', date: time_ago_in_words(@post.created_at))
      .ms-auto#likes-section
        span.me-3
        - if @current_user_like
          = link_to post_like_path(@post, @current_user_like), method: :delete, class: 'text-decoration-none link-danger' do
            span.text-muted.me-2= @post.likes.size
            i.fas.fa-heart
        - else
          = link_to post_likes_path(@post), method: :post, class: 'text-decoration-none link-secondary' do
            span.text-muted.me-2= @post.likes.size
            i.fas.fa-heart
    - if @post.creator == @current_user
      small
        = link_to t(:edit), edit_post_path(@post), class: 'me-2'
        = link_to t(:destroy), @post, method: :delete, data: { confirm: t(:destroy_confirmation) }, class: 'link-danger'
- if user_signed_in?
  .lead.m3
    = t('.comment')
  = render 'posts/comments/form', comment: @comment, url: post_comments_path(@post)
= render partial: 'posts/comments/comment', collection: @comment_collection